### ISSUE TITLE
NVidia GSP randomly crashes Wayland session

### ISSUE THREAD

**Issue by leleobhz** [CachyOS/distribution#109]
Hello!

System report: https://paste.cachyos.org/p/46829b6.log

After last kernel+nvidia driver upgrade [1], my system randomly crashes. The previous boot log contains the following entries:

```
[root@miriam ~]# journalctl --utc --boot=-1 | grep NVRM
abr 08 12:39:04 miriam kernel: NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  570.133.07  Release Build  (notroot@34a3ffbed8a3)  Fri Mar 28 11:18:11 UTC 2025
abr 08 12:39:05 miriam kernel: NVRM: _intrInitRegistryOverrides: NV_REG_STR_RM_INTR_LOCKING_MODE was set to: 0x1
abr 08 18:10:23 miriam kernel: NVRM: nvAssertFailedNoLog: Assertion failed: CliGetEventInfo(rpc_params->hClient, rpc_params->hEvent, &pEvent) @ kernel_gsp.c:467
abr 08 18:10:23 miriam kernel: NVRM: _kgspProcessRpcEvent: Failed to process received event 0x1003 (POST_EVENT) from GPU0: status=0x57
```

First 2 lines is normal boot. 2 last lines happens in same moment screen freezes. Applications keep running (Eg. Music keeps playing and being controlled by Bluetooth controls), but image got entirelly frozen. Also I was unable to access framebuffer terminals.

Behavior is the same reported at https://forums.developer.nvidia.com/t/2nd-monitor-frozen-recent-freezing/325588 nvidia forum post. A relevant information: This post says about 2nd monitor and I do not have a second monitor plugged right now, but I have a displaylink monitor that I use sometimes, so evdi and displaylink daemon are loaded. I tried now to disable it.

Since this may be GSP related issue, I've disabled GSP:

```
[root@miriam ~]# cat /etc/modprobe.d/nvidia-gsp.conf
options nvidia NVreg_EnableGpuFirmware=0
```

And my system is running (but not sure about stability since I just restarted it).

That said and considering CachyOS tells this option is not appliable while using open source drivers (https://wiki.cachyos.org/configuration/general_system_tweaks/#nvidia-gsp-firmware), I do not know how to proceed to troubleshoot it. Can CachyOS Dev team help-me to find out what happened?

Thanks!

[1]:

```
❯ LANG=C paru -Qi linux-cachyos-nvidia-open
Installed From  : cachyos-v4
Name            : linux-cachyos-nvidia-open
Version         : 6.14.0-4
Description     : nvidia open modules of 570.133.07 driver for the linux-cachyos kernel
Architecture    : x86_64_v4
URL             : https://github.com/CachyOS/linux-cachyos
Licenses        : MIT AND GPL-2.0-only
Groups          : None
Provides        : NVIDIA-MODULE
Depends On      : linux-cachyos=6.14.0-4  nvidia-utils=570.133.07  libglvnd
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : linux-cachyos-nvidia
Replaces        : None
Installed Size  : 18,42 MiB
Packager        : CachyOS <admin@cachyos.org>
Build Date      : sex 28 mar 2025 07:53:33
Install Date    : dom 06 abr 2025 09:37:35
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by ptr1337** [comment]
Hi,

Thank you for the report
This is a known issue, which is tracked here: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/739

You should be able to recover with switching the tty. I do not suspect this is due the recent kernel upgrade. The issue is happening fully randomly and it is not root caused yet.

If you want to disable the GSP Firmware, then you also need the closed source nvidia module:
```
sudo pacman -S linux-cachyos-nvidia
```

I do not know, if related but we apply the high refresh rate optimization. Since in the log it appears to print:
`NV_REG_STR_RM_INTR_LOCKING_MODE` you can try to disable this, see below link.

https://github.com/CachyOS/CachyOS-Settings/blob/a7b5af383eea9b8ef0d23beaf6f70340a46f236f/usr/lib/modprobe.d/nvidia.conf#L22-L24

**Comment by leleobhz** [comment]
Hello @ptr1337 

My issue does behave a bit different from what you reported at https://github.com/NVIDIA/open-gpu-kernel-modules/issues/739#issuecomment-2487900831

I do not have 2 monitors currently running (Crash also happened with evdi/displaylink disabled) and my main monitor got frozen.

Also, tty switch also not work. Nothing from keyboard reacts after this crash. I ssh'ed my machine and restarted `gdm.service` to get my screen working again. More or less the same from https://github.com/NVIDIA/open-gpu-kernel-modules/issues/739#issuecomment-2489410621 comment.

Also, I switched to Xorg Gnome session and crash haven't happened.

What do you think it's the best to do?

**Comment by 1Naim** [comment]
> System report: https://paste.cachyos.org/p/46829b6.log

Your log looks malformed, it's not showing the installed custom packages for some reason. Either way, there's a new kernel 6.14.1, can you update your system and try to reproduce again?

Thanks.

**Comment by leleobhz** [comment]
> > System report: https://paste.cachyos.org/p/46829b6.log
> 
> Your log looks malformed, it's not showing the installed custom packages for some reason. Either way, there's a new kernel 6.14.1, can you update your system and try to reproduce again?
> 
> Thanks.

Hello @1Naim 

I'll upgrade it and test it. About log malformed, the proper command is right one?

```
++ get_installed_packages
++ '[' -e /var/lib/pacman/sync/cachyos-v4.db ']'
++ pacman -Ss
++ grep --color=never '^cachyos-v4/.*\[installed\]'
+ upload
+ ask_yes_no 'Do you want to upload this log to https://paste.cachyos.org?'
```

For me apparently cachyos-bugreport misses `LANG=C` to avoid localization while grepping:

```
❯ sudo LANG=C pacman -Ss | grep --color=never '^cachyos-v4/.*\[installed\]'
cachyos-v4/bash 5.2.037-2 [installed]
cachyos-v4/binutils 2.44-3 [installed]
cachyos-v4/clang 19.1.7-2 [installed]
cachyos-v4/gcc 14.2.1+r753+g1cd744a6828f-2 [installed]
cachyos-v4/gcc-libs 14.2.1+r753+g1cd744a6828f-2 [installed]
cachyos-v4/glibc 2.41+r9+ga900dbaf70f0-2 [installed]
cachyos-v4/go 2:1.24.1-2 [installed]
cachyos-v4/lib32-gcc-libs 14.2.1+r753+g1cd744a6828f-2 [installed]
cachyos-v4/lib32-glibc 2.41+r9+ga900dbaf70f0-2 [installed]
cachyos-v4/lib32-mesa 1:25.0.3-2 [installed]
cachyos-v4/lib32-nvidia-utils 570.133.07-2 [installed]
cachyos-v4/lib32-zlib-ng 2.2.4-1 [installed]
cachyos-v4/lib32-zlib-ng-compat 2.2.4-1 [installed]
cachyos-v4/lib32-zstd 1.5.7-2 [installed]
cachyos-v4/libtool 2.5.4+r1+gbaa1fe41-4 [installed]
cachyos-v4/libxnvctrl 570.124.04-2 [installed]
cachyos-v4/linux-api-headers 1:6.13-2 [installed]
cachyos-v4/linux-cachyos 6.14.0-4 [installed]
cachyos-v4/linux-cachyos-headers 6.14.0-4 [installed]
cachyos-v4/linux-cachyos-lts 6.12.19-2 [installed]
cachyos-v4/linux-cachyos-lts-headers 6.12.19-2 [installed]
cachyos-v4/linux-cachyos-lts-nvidia-open 6.12.19-2 [installed]
cachyos-v4/linux-cachyos-nvidia-open 6.14.0-4 [installed]
cachyos-v4/llvm 19.1.7-2 [installed]
cachyos-v4/llvm-libs 19.1.7-2 [installed]
cachyos-v4/lz4 1:1.10.0-3 [installed]
cachyos-v4/mesa 1:25.0.3-2 [installed]
cachyos-v4/nvidia-settings 570.124.04-2 [installed]
cachyos-v4/nvidia-utils 570.133.07-2 [installed]
cachyos-v4/proton-cachyos 1:9.0.20250402-1 [installed]
cachyos-v4/python 3.13.2-2 [installed]
cachyos-v4/ripgrep 14.1.1-2 [installed]
cachyos-v4/scx-scheds 1.0.11-2 [installed]
cachyos-v4/svt-av1 3.0.2-2 [installed]
cachyos-v4/wine-cachyos 2:9.0.20250402-1 [installed]
cachyos-v4/wine-cachyos-opt 2:9.0.20250402-1 [installed]
cachyos-v4/xz 5.8.0-2 [installed]
cachyos-v4/zlib-ng 2.2.4-1 [installed]
cachyos-v4/zlib-ng-compat 2.2.4-1 [installed]
cachyos-v4/zstd 1.5.7-2 [installed]
```

This deserves a bugreport?

**Comment by 1Naim** [comment]
> For me apparently cachyos-bugreport misses `LANG=C` to avoid localization while grepping

Ack, we should fix this on our side. Thanks for letting us know.

**Comment by 1Naim** [comment]
```
[  421.719591] [drm:nv_drm_connector_get_modes [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00006500] Failed to get mode at modeIndex 25 of NvKmsKapiDisplay 0x00000400
```

Looks like there's something new here. I also reread this whole thread and I see that you haven't really tried disabling GSP. Can tou try and do that? I'm also crossing my fingers here that 6.14.2 fixes this but probably not...

**Comment by ptr1337** [comment]
Would be also good, if you report it directly to NVIDIA

**Comment by leleobhz** [comment]
> haven't really tried disabling GSP

Hello @1Naim 

nvidia-open still not supporting GSP disablement? I've followed CachyOS documentation for troubleshooting this issue and this is the first thing I've hit. Anyways, I took configuration in place since this happened first time: 

```
[root@miriam ~]# cat /etc/modprobe.d/nvidia-gsp.conf
options nvidia NVreg_EnableGpuFirmware=0
```

> Would be also good, if you report it directly to NVIDIA

Hello @ptr1337 

This report is done within forums or there is another way to report it to NVidia?

**Comment by 1Naim** [comment]
> nvidia-open still not supporting GSP disablement?

Well, yeah. You need to switch to the closed modules. `sudo pacman -S linux-cachyos-nvidia`, or can you not do that for some reason?

> there is another way to report it to NVidia?

You can email them directly, although I don't have the email address off the top of my head.

**Comment by leleobhz** [comment]
> Well, yeah. You need to switch to the closed modules. `sudo pacman -S linux-cachyos-nvidia`, or can you not do that for some reason?
> 

Hello @1Naim 

No reason here. In fact Im unable to understand* the feature hole between nvidia-open and nvidia-closed. I just use cachyos "as is" for GPU subject ones (As the same i just "use" photon-cachyos because graphics and gaming is things I just use, I do not develop it as SRE).

That said, what may happen if I change to nvidia-closed source ones? I may have any known drawback?







* But someone can understand what nvidia does on their drivers?

**Comment by 1Naim** [comment]
> That said, what may happen if I change to nvidia-closed source ones? I may have any known drawback

There should be no functional changes, but bugs in each implementation do exist. For instance, whatever you're experiencing now could be a GSP bug, and if it is, then this bug will not be present in the closed driver. The closed driver may have its own bugs too.

**Comment by 1Naim** [comment]
Has there been any updates after these past 3 months?
